SYSCONF_LINK = g++
CPPFLAGS	 = -Wall -std=c++14
LDFLAGS		 = -O3
LIBS		 = -lm
INC			 = -I./include

# Additional folders for file look up
VPATH 	= src:include
DESTDIR = ./
TARGET  = TinyRenderer

# Replace all found cpp files to .o for prerequisites
OBJECTS = $(patsubst %.cpp,%.o,$(wildcard src/*.cpp))

all: $(DESTDIR)$(TARGET)

# Rule to create the executable
$(DESTDIR)$(TARGET): $(OBJECTS)
	$(SYSCONF_LINK) -Wall $(LDFLAGS) -o $(DESTDIR)$(TARGET) $(OBJECTS) $(LIBS)

# Rule to create .o files, needs the include path
$(OBJECTS): %.o: %.cpp
	$(SYSCONF_LINK) -Wall $(CPPFLAGS) $(INC) -c $(CFLAGS) $< -o $@

clean:
	-rm -f $(OBJECTS)
	-rm -f $(TARGET)
	-rm -f *.tga